apiVersion: apps/v1
kind: Deployment
metadata:
  name: rcmdfeng-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rcmdfeng
  template:
    metadata:
      labels:
        app: rcmdfeng
    spec:
      containers:
        - name: rcmdfeng
          image: rcmdacr.azurecr.io/rcmdfeng:latest
          ports:
            - containerPort: 80
